### ISSUE TITLE
Issue with infinite loops

### ISSUE THREAD

**Issue by FlipzMCL** [fnuecke/CraftingCosts#4]
In testing CraftingCosts with Per Fabrica Ad Astra and GregTech, I found that the mod gets caught up in infinite loops because these mods add recipes for things like cobble and metals (i.e. Stone in a Macerator creates Cobblestone, GregTech adds several recipes for converting iron and other metals between various mods' versions), as well as CraftingCosts looking up recipes for tools used in recipes leading to even more infinite loops (i.e. there's a recipe for sticks that uses a saw, but a saw is made with sticks).

In discussing with the other players on the server at the time, we came up with the idea of allowing a config that sets certain materials (i.e. cobblestone, tools, etc.) as absolute base states, so that CraftingCosts won't look up recipes for these items as defined in the config file. :-)

**Comment by fnuecke** [comment]
Thanks! Yeah, some mods introduce recipe chains that make the search-space insanely huge, I have some ideas how to tackle this - will look into implementing them ~~in the afternoon~~.

In 1.0.1 many "basic" items have been added to the black list, making them serve as base states as you suggest! Just make sure to delete your config when updating from 1.0.1 to make sure the new defaults get written. _grumblessomethingaboutaddingversionnumbertoconfigtodothisautomatically_
